version: 0.0
os: linux

files:
  - source: /
    destination: /var/www
permissions:
  - object: /var/www
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 400
      runas: ubuntu
      commands:
        - chmod +x scripts/deploy.sh
        - ./scripts/deploy.sh
